//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.8.2
//     from Assets/Scripts/Input/R8EOXInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;
using UnityEngine;

namespace R8EOX.Input
{
    public partial class @R8EOXInputActions: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @R8EOXInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""R8EOXInputActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""a1b2c3d4-e5f6-7890-abcd-ef1234567890"",
            ""actions"": [
                {
                    ""name"": ""Steer"",
                    ""type"": ""Value"",
                    ""id"": ""b1000001-0000-0000-0000-000000000001"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Throttle"",
                    ""type"": ""Value"",
                    ""id"": ""b1000002-0000-0000-0000-000000000002"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Brake"",
                    ""type"": ""Value"",
                    ""id"": ""b1000003-0000-0000-0000-000000000003"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""b1000004-0000-0000-0000-000000000004"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""b1000005-0000-0000-0000-000000000005"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraCycle"",
                    ""type"": ""Button"",
                    ""id"": ""b1000006-0000-0000-0000-000000000006"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraOrbit"",
                    ""type"": ""Value"",
                    ""id"": ""b1000007-0000-0000-0000-000000000007"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraOrbitEnable"",
                    ""type"": ""Button"",
                    ""id"": ""b1000008-0000-0000-0000-000000000008"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugToggle"",
                    ""type"": ""Button"",
                    ""id"": ""b1000009-0000-0000-0000-000000000009"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TuningToggle"",
                    ""type"": ""Button"",
                    ""id"": ""b100000a-0000-0000-0000-00000000000a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c1000001-0000-0000-0000-000000000001"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(min=0.2)"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Steer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""c1000002-0000-0000-0000-000000000002"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c1000003-0000-0000-0000-000000000003"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""Steer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""c1000004-0000-0000-0000-000000000004"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""Steer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c1000005-0000-0000-0000-000000000005"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.15)"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1000006-0000-0000-0000-000000000006"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1000007-0000-0000-0000-000000000007"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.15)"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1000008-0000-0000-0000-000000000008"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1000009-0000-0000-0000-000000000009"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c100000a-0000-0000-0000-00000000000a"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c100000b-0000-0000-0000-00000000000b"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c100000c-0000-0000-0000-00000000000c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c100000d-0000-0000-0000-00000000000d"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CameraCycle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c100000e-0000-0000-0000-00000000000e"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""CameraCycle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c100000f-0000-0000-0000-00000000000f"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CameraOrbit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1000010-0000-0000-0000-000000000010"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""CameraOrbitEnable"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1000011-0000-0000-0000-000000000011"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""DebugToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1000012-0000-0000-0000-000000000012"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard+Mouse"",
                    ""action"": ""TuningToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard+Mouse"",
            ""bindingGroup"": ""Keyboard+Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Gameplay
            m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
            m_Gameplay_Steer = m_Gameplay.FindAction("Steer", throwIfNotFound: true);
            m_Gameplay_Throttle = m_Gameplay.FindAction("Throttle", throwIfNotFound: true);
            m_Gameplay_Brake = m_Gameplay.FindAction("Brake", throwIfNotFound: true);
            m_Gameplay_Reset = m_Gameplay.FindAction("Reset", throwIfNotFound: true);
            m_Gameplay_Pause = m_Gameplay.FindAction("Pause", throwIfNotFound: true);
            m_Gameplay_CameraCycle = m_Gameplay.FindAction("CameraCycle", throwIfNotFound: true);
            m_Gameplay_CameraOrbit = m_Gameplay.FindAction("CameraOrbit", throwIfNotFound: true);
            m_Gameplay_CameraOrbitEnable = m_Gameplay.FindAction("CameraOrbitEnable", throwIfNotFound: true);
            m_Gameplay_DebugToggle = m_Gameplay.FindAction("DebugToggle", throwIfNotFound: true);
            m_Gameplay_TuningToggle = m_Gameplay.FindAction("TuningToggle", throwIfNotFound: true);
        }

        ~@R8EOXInputActions()
        {
            Debug.Assert(!m_Gameplay.enabled, "This will cause a leak and performance issues, R8EOXInputActions.Gameplay.Disable() has not been called.");
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Gameplay
        private readonly InputActionMap m_Gameplay;
        private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
        private readonly InputAction m_Gameplay_Steer;
        private readonly InputAction m_Gameplay_Throttle;
        private readonly InputAction m_Gameplay_Brake;
        private readonly InputAction m_Gameplay_Reset;
        private readonly InputAction m_Gameplay_Pause;
        private readonly InputAction m_Gameplay_CameraCycle;
        private readonly InputAction m_Gameplay_CameraOrbit;
        private readonly InputAction m_Gameplay_CameraOrbitEnable;
        private readonly InputAction m_Gameplay_DebugToggle;
        private readonly InputAction m_Gameplay_TuningToggle;
        public struct GameplayActions
        {
            private @R8EOXInputActions m_Wrapper;
            public GameplayActions(@R8EOXInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Steer => m_Wrapper.m_Gameplay_Steer;
            public InputAction @Throttle => m_Wrapper.m_Gameplay_Throttle;
            public InputAction @Brake => m_Wrapper.m_Gameplay_Brake;
            public InputAction @Reset => m_Wrapper.m_Gameplay_Reset;
            public InputAction @Pause => m_Wrapper.m_Gameplay_Pause;
            public InputAction @CameraCycle => m_Wrapper.m_Gameplay_CameraCycle;
            public InputAction @CameraOrbit => m_Wrapper.m_Gameplay_CameraOrbit;
            public InputAction @CameraOrbitEnable => m_Wrapper.m_Gameplay_CameraOrbitEnable;
            public InputAction @DebugToggle => m_Wrapper.m_Gameplay_DebugToggle;
            public InputAction @TuningToggle => m_Wrapper.m_Gameplay_TuningToggle;
            public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
            public void AddCallbacks(IGameplayActions instance)
            {
                if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
                @Steer.started += instance.OnSteer;
                @Steer.performed += instance.OnSteer;
                @Steer.canceled += instance.OnSteer;
                @Throttle.started += instance.OnThrottle;
                @Throttle.performed += instance.OnThrottle;
                @Throttle.canceled += instance.OnThrottle;
                @Brake.started += instance.OnBrake;
                @Brake.performed += instance.OnBrake;
                @Brake.canceled += instance.OnBrake;
                @Reset.started += instance.OnReset;
                @Reset.performed += instance.OnReset;
                @Reset.canceled += instance.OnReset;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @CameraCycle.started += instance.OnCameraCycle;
                @CameraCycle.performed += instance.OnCameraCycle;
                @CameraCycle.canceled += instance.OnCameraCycle;
                @CameraOrbit.started += instance.OnCameraOrbit;
                @CameraOrbit.performed += instance.OnCameraOrbit;
                @CameraOrbit.canceled += instance.OnCameraOrbit;
                @CameraOrbitEnable.started += instance.OnCameraOrbitEnable;
                @CameraOrbitEnable.performed += instance.OnCameraOrbitEnable;
                @CameraOrbitEnable.canceled += instance.OnCameraOrbitEnable;
                @DebugToggle.started += instance.OnDebugToggle;
                @DebugToggle.performed += instance.OnDebugToggle;
                @DebugToggle.canceled += instance.OnDebugToggle;
                @TuningToggle.started += instance.OnTuningToggle;
                @TuningToggle.performed += instance.OnTuningToggle;
                @TuningToggle.canceled += instance.OnTuningToggle;
            }

            private void UnregisterCallbacks(IGameplayActions instance)
            {
                @Steer.started -= instance.OnSteer;
                @Steer.performed -= instance.OnSteer;
                @Steer.canceled -= instance.OnSteer;
                @Throttle.started -= instance.OnThrottle;
                @Throttle.performed -= instance.OnThrottle;
                @Throttle.canceled -= instance.OnThrottle;
                @Brake.started -= instance.OnBrake;
                @Brake.performed -= instance.OnBrake;
                @Brake.canceled -= instance.OnBrake;
                @Reset.started -= instance.OnReset;
                @Reset.performed -= instance.OnReset;
                @Reset.canceled -= instance.OnReset;
                @Pause.started -= instance.OnPause;
                @Pause.performed -= instance.OnPause;
                @Pause.canceled -= instance.OnPause;
                @CameraCycle.started -= instance.OnCameraCycle;
                @CameraCycle.performed -= instance.OnCameraCycle;
                @CameraCycle.canceled -= instance.OnCameraCycle;
                @CameraOrbit.started -= instance.OnCameraOrbit;
                @CameraOrbit.performed -= instance.OnCameraOrbit;
                @CameraOrbit.canceled -= instance.OnCameraOrbit;
                @CameraOrbitEnable.started -= instance.OnCameraOrbitEnable;
                @CameraOrbitEnable.performed -= instance.OnCameraOrbitEnable;
                @CameraOrbitEnable.canceled -= instance.OnCameraOrbitEnable;
                @DebugToggle.started -= instance.OnDebugToggle;
                @DebugToggle.performed -= instance.OnDebugToggle;
                @DebugToggle.canceled -= instance.OnDebugToggle;
                @TuningToggle.started -= instance.OnTuningToggle;
                @TuningToggle.performed -= instance.OnTuningToggle;
                @TuningToggle.canceled -= instance.OnTuningToggle;
            }

            public void RemoveCallbacks(IGameplayActions instance)
            {
                if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IGameplayActions instance)
            {
                foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public GameplayActions @Gameplay => new GameplayActions(this);
        private int m_KeyboardMouseSchemeIndex = -1;
        public InputControlScheme KeyboardMouseScheme
        {
            get
            {
                if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard+Mouse");
                return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
            }
        }
        private int m_GamepadSchemeIndex = -1;
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
        public interface IGameplayActions
        {
            void OnSteer(InputAction.CallbackContext context);
            void OnThrottle(InputAction.CallbackContext context);
            void OnBrake(InputAction.CallbackContext context);
            void OnReset(InputAction.CallbackContext context);
            void OnPause(InputAction.CallbackContext context);
            void OnCameraCycle(InputAction.CallbackContext context);
            void OnCameraOrbit(InputAction.CallbackContext context);
            void OnCameraOrbitEnable(InputAction.CallbackContext context);
            void OnDebugToggle(InputAction.CallbackContext context);
            void OnTuningToggle(InputAction.CallbackContext context);
        }
    }
}
